 Loops:      250722 Time[Ma]:  0.13241280604975902     
  Found at (i,j)          64          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      250722 Time[Ma]:  0.13241280604975902     
  Found at (i,j)          65          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      250722 Time[Ma]:  0.13241280604975902     
  Found at (i,j)          65          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          51          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          50          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          50          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          52          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          62          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          64          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      278580 Time[Ma]:  0.14712539873632477     
  Found at (i,j)          64          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          30  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          30  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          30  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          30  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          31  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          50          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          32  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          51          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          52          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          53          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          34  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          54          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          55          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          56          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          33  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          58          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          57          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          59          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      334296 Time[Ma]:  0.17655058410986355     
  Found at (i,j)          60          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          66          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          35  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          66          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          67          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          67          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          67          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          67          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          67          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          67          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          68          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          70          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          70          36  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          70          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          71          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          70          37  Might need more frequent remeshing?                                                                                                                            
 Loops:      668592 Time[Ma]:  0.35310169634673838     
  Found at (i,j)          69          37  Might need more frequent remeshing?                                                                                                                            
